version: "3.7"

services:      
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - default
      - docker_default
    ports:
    - "3306:3306"

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
      - REDIS_CACHE=redis://:difyai123456@redis:6379/0
      - REDIS_QUEUE=redis://:difyai123456@redis:6379/1
      - REDIS_SOCKETIO=redis://:difyai123456@redis:6379/2
      - AGENT_API_KEY=${AGENT_API_KEY}
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - default
      - docker_default

volumes:
  mariadb-data:

networks:
  docker_default:
    external: true